### PR TITLE
Use asynchronous DBus proxy creation

### LINKED ISSUE #159: Doesn't work properly under Wayland
I've tried this extension under Wayland (Fedora 25), but it doesn't work on login. It reports a timeout error connecting to hamster DBus service (don't have the exact error message right now, can report later). 

Surprisingly, sometimes it suddenly starts to work (probably after locking/unlocking the screen or some other events, but have not found the exact procedure to make it appear). But it doesn't work right after login anyway.

**Update:** error message:
Gio.IOErrorEnum: Error calling StartServiceByName for org.gnome.Hamster: Timeout was reached

And current running services:
% pgrep -af hamster
10067 python2 /usr/bin/hamster-service

hamster-windows-service seems to be unable to run automatically when using Wayland, but works fine under X.

### PR DESCRIPTION
**Pull request by hedayat**
This fixes gnome-shell freezes under Wayland (at least in Fedora), as it
seems that it stalls gnome-shells main loop. fixes #159

### CODE REVIEW

**Comment by hedayat** [comment]
First let me confess:
1. I tried to fix the problem with minimal effort
2. I'm neither know about gnome shell extensions, nor good at Javascript

So, it is likely that the code is neither clean nor readable enough. And I see that it is not readable enough. Maybe it is more readable if they both call deferred_enable, and it checks if both proxies are not null before continuing.

But no, it doesn't call deferred_enable twice (I assumed that the code is async but executed in a single thread, and it seems to be the case).
So, one of the callbacks are called first, and in that case the other proxy is still null, so the condition fails and it won't call deferred_enable(). Then, the other callback is called when the second proxy is created, and the condition passes since the other proxy is already created, and it'll call deferred_enable(). So, the code ensures that deferred_call() is called once when both proxies are created. (If both if() conditions are removed, it'll be called twice).

But I'd appreciate if somebody else makes the code more readable; as I'm both a bit tight on time and not confident that what I write is the best that can be done with Javascript.

**Comment by hedayat** [comment]
But there is one problematic area: if disable() is called after enable() but before dbus services are started (and so, before deferred_enable()), deferred_enable() will be called after disable(), which won't be desirable. Won't happen normally, but still..

**Comment by hedayat** [comment]
I changed the code a bit, to prevent the problem I said above and probably a bit more readable.

**Comment by elbenfreund** [comment]
Thanks for your feedback and elaborations. I took the liberty to add some docstrings/comments.
Other than that, i think the code looks great. :+1:

**Comment by hedayat** [comment]
Thanks. Looks great. :)

**Comment by elbenfreund** [comment]
Do you mind if I squash the commits and force push?

**Comment by hedayat** [comment]
Nope, feel free to do what you like. It's yours :)

**Pull request merged**
